[Logger]
#число лог-файлов в ротации
fnum=4
#предельный размер одного файла в байтах
fsize=1000000
#ориентир максимального количества сообщений в памяти до сброса на диск
mmax=100
#путь к лог-файлу (если не подходит расположение в папке с исполняемым файлом)
fpath=
#предельное разрешенное время сна потока логгера в микросекундах
stime=10000
#уровень логирования (SPEC, DEBUG, INFO, WARN, ERROR, OFF)
level=DEBUG

#Параметры запуска Wt::WServer, см.библиотеку Wt
[WServer]
docroot=.
#http удобен для отладки. А https - для рабочей системы. Оба не могут быть указаны.
http-listen=0.0.0.0:8089
#https-listen=0.0.0.0:443
#пути к файлам сертификата ssl
ssl-certificate=/your_path_to_cert/fullchain.pem
ssl-private=/your_path_to_priv/privkey.pem
#сгенерированный Diffie-Hellman файл: openssl dhparam -out dhparam.pem 2048 
ssl-tmp-dh=/your_path_to_dh/dhparam.pem

#Параметры доступа к базе данных
[MySQL]
host=localhost
port=33060
user=your_user
pass=your_password
db=your_database

#Общие настройки
[Settings]
#команда отправки параметры - "кому" "заголовок" "текст"  Пароль в файле
#mailcmd=sendemail.sh 
#Адрес администратора, которому будут в полночь слаться отчеты о работе программы
#mailto=admin_email@your_server.ru
#вспомогательный параметер для ориентации сообщений на экране
msgbox_offset=20vh
#время в течение которого внешнему сервису не будет отправляться обновление, если статус устройства не поменялся. Служит для сокращения количества исходящих запросов.
secondsUnchanged=600
#Доменное имя, которое будет использовать при отправке имэйл для смены пароля
#domain=your_site.ru

[Client_ids]
#каждый ключ - Client ID из настроек облачного сервиса. Каждому client id соответствует имя сервиса, которое будет использоваться в логах.
#при этом client id может быть и "заглушкой", например в случае прямых запросов от голосового помощника, без авторизации через OAuth 2.0.
your_id_at_yandex=Yandex
#для VK настроек нет, так как VK не принимает запросы от устройств, только опрашивает
your_id_at_vk=VK
id_for_salute=Salute
id_for_signal=SmartDevice
id_for_alice=Alice

#Имя каждой секции - это client id из секции Client_ids. У каждого сервиса могут быть адреса для обновления статусов и запроса на обновление описаний устройств.
#Если нет секции или ее ключи пусты, то действий (например отправки статуса устройства при его изменении) программа выполнять не будет.
#Это актуально, например для VK, у которого нет API для этого, используется polling. А также для приложений голосовых помощников, которые не относятся к типу "Умный дом".
#Все возможные ключи описаны в struct externalService, файл main.cpp

[your_id_at_yandex]
out_token=получите в Яндексе
out_skill_id=возьмите из адресной строки браузера когда редактируете навык

[id_for_salute]
in_token=придумайте сами и используйте его в настройка смартапа

[id_for_signal]
in_token=придумайте сами, этот токен надо использовать при обновлении статуса устройства самим устройством или умным домом при обращении к шлюзу

[id_for_alice]
user_ids=найдите_в_теле_запроса_user_id:ваши_инициалы, тоже_самое_для_другого_акаунта_которому_дан_доступ_к_навыку:TM

